server:
  port: 8873

spring:
  application:
    name: monitor-service

# 注册中心配置
eureka:
  instance:
    ip-address: 127.0.0.1
    port: 8761
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${eureka.instance.port}/eureka/